### ISSUE TITLE
Bug in merge_components method

### ISSUE THREAD

**Issue by peter42csontos** [IsaacCheng9/boruvkas-algorithm#2]
I can’t create a PR now, but here’s the fix with explanation in comments:

    def merge_components(
...
        # Merge the smaller component into the larger component.
        if component_sizes[vertex1_component] < component_sizes[vertex2_component]:
            # BUG: the line commented out below is wrong in 2 ways:
            # 1. the keys of this dictionary are vertices and not components,
            # 2. all the impacted vertices should be moved, not just one.
            # The same applies to the else branch as well
            # vertex_to_component[vertex1_component] = vertex2_component
            # NEW CODE BEGINS
            for v in vertex_to_component:
                if vertex_to_component[v] == vertex1_component:
                    vertex_to_component[v] = vertex2_component
            # NEW CODE ENDS
            component_sizes[vertex2_component] += component_sizes[vertex1_component]
        else:
            # vertex_to_component[vertex2_component] = vertex1_component
            # NEW CODE BEGINS
            for v in vertex_to_component:
                if vertex_to_component[v] == vertex2_component:
                    vertex_to_component[v] = vertex1_component
            # NEW CODE ENDS
            component_sizes[vertex1_component] += component_sizes[vertex2_component]

**Comment by IsaacCheng9** [comment]
Thanks for pointing that out – I'll look at changing this.
